apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: reader-service-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "django-api/uat/db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_USER
            objectAlias: db-user
          - path: DB_PASSWORD
            objectAlias: db-password
          - path: DB_HOST
            objectAlias: db-host
          - path: DB_NAME
            objectAlias: db-name
          - path: DB_PORT
            objectAlias: db-port
  secretObjects:
    - secretName: reader-service-db-secret
      type: Opaque
      data:
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: db-host
          key: DB_HOST
        - objectName: db-name
          key: DB_NAME
        - objectName: db-port
          key: DB_PORT
