apiVersion: v1
kind: Service
metadata:
  name: reader-service
  namespace: default
  labels:
    app: reader-service
spec:
  type: ClusterIP
  selector:
    app: reader-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
