apiVersion: v1
kind: Service
metadata:
  name: writer-service
  namespace: default
  labels:
    app: writer-service
spec:
  type: ClusterIP
  selector:
    app: writer-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
